cabal-version: 3.0
name: notizfaden
version: 0.1.0.0
build-type: Simple

executable notizfaden-server
  main-is: Main.hs
  hs-source-dirs: src
  other-modules: Auth, Database, Model, Notes
  default-language: GHC2021
  ghc-options: -Wall -threaded -rtsopts -with-rtsopts=-N2
  build-depends:
    base >=4.18 && <5,
    aeson >=2.2,
    bytestring,
    text,
    time,
    containers,
    uuid,
    crypton,
    memory,
    postgresql-simple,
    servant-server,
    wai,
    wai-cors,
    warp,
    http-types
