import { test, expect } from '@playwright/test';

test('local notes: autosave, labels, search, checklist, archive, trash and restore', async ({ page }) => {
  await page.goto('/');
  await expect(page.getByTestId('note-card')).toHaveCount(8);
  await page.getByRole('button', { name: '메모 작성…', exact: true }).click();
  await page.getByRole('textbox', { name: '메모 제목' }).fill('브라우저 검증 메모');
  await page.getByRole('textbox', { name: '메모 내용' }).fill('한글 자동 저장\n아직 정리되지 않은 생각');
  await page.getByRole('button', { name: '색상 바꾸기', exact: true }).last().click();
  await page.getByRole('button', { name: '민트', exact: true }).click();
  await page.getByRole('button', { name: '라벨 추가', exact: true }).click();
  await page.getByRole('textbox', { name: '새 라벨' }).fill('검증');
  await page.getByRole('button', { name: '추가', exact: true }).click();
  await page.getByRole('button', { name: '닫기', exact: true }).click();
  await page.reload();
  await expect(page.getByText('브라우저 검증 메모', { exact: true })).toBeVisible();
  await page.getByRole('searchbox').fill('한글 자동');
  await expect(page.getByTestId('note-card')).toHaveCount(1);
  const card = page.getByTestId('note-card');
  await card.hover();
  await card.getByRole('button', { name: '메모 보관', exact: true }).click();
  await page.getByRole('button', { name: '보관함', exact: true }).click();
  await expect(page.getByText('브라우저 검증 메모', { exact: true })).toBeVisible();
  await page.getByTestId('note-card').hover();
  await page.getByRole('button', { name: '휴지통으로 이동', exact: true }).click();
  await page.getByRole('button', { name: '휴지통', exact: true }).click();
  await expect(page.getByText('브라우저 검증 메모', { exact: true })).toBeVisible();
  await page.getByTestId('note-card').hover();
  await page.getByRole('button', { name: '메모 복원', exact: true }).click();
  await expect(page.getByText('휴지통이 비어 있어요')).toBeVisible();
  await page.getByRole('button', { name: '메모', exact: true }).click();
  await page.getByRole('button', { name: '새 체크리스트', exact: true }).click();
  await page.getByRole('textbox', { name: '메모 제목' }).fill('체크리스트 검증');
  await page.getByRole('button', { name: '목록 항목', exact: true }).click();
  await page.getByRole('textbox', { name: '항목 1', exact: true }).fill('첫 항목');
  await page.getByRole('textbox', { name: '항목 1', exact: true }).press('Enter');
  await page.getByRole('textbox', { name: '항목 2', exact: true }).fill('둘째 항목');
  await page.getByRole('checkbox', { name: '첫 항목 완료' }).check();
  await page.getByRole('button', { name: '닫기', exact: true }).click();
  await page.reload();
  await expect(page.getByRole('checkbox', { name: '첫 항목', exact: true })).toBeChecked();
});

test('mobile layout and dark theme preserve local data', async ({ page }) => {
  await page.setViewportSize({ width: 390, height: 844 });
  await page.goto('/');
  await expect(page.getByTestId('note-card')).toHaveCount(8);
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBeTruthy();
  await page.getByRole('button', { name: '어두운 테마', exact: true }).click();
  await page.getByRole('button', { name: '메모 작성…', exact: true }).click();
  await page.getByRole('textbox', { name: '메모 내용' }).fill('모바일에서 적은 메모');
  await page.getByRole('button', { name: '메모 닫기', exact: true }).click();
  await page.reload();
  await expect(page.locator('html')).toHaveAttribute('data-theme', 'dark');
  await expect(page.getByText('모바일에서 적은 메모', { exact: true })).toBeVisible();
});

test('account, two devices, public feed, fork and unpublish use the Haskell API', async ({ page, browser }) => {
  const username = 'ui_' + Date.now();
  const password = 'teum-browser-test-2026';
  await page.goto('/');
  await page.getByRole('button', { name: '로그인', exact: true }).click();
  await page.getByRole('button', { name: '처음 오셨나요? 계정 만들기' }).click();
  await page.getByRole('textbox', { name: '아이디', exact: true }).fill(username);
  await page.getByLabel('비밀번호', { exact: true }).fill(password);
  await page.getByRole('button', { name: '메모장 만들기', exact: true }).click();
  await expect(page.getByRole('dialog')).toHaveCount(0);
  await page.getByRole('button', { name: '메모 작성…', exact: true }).click();
  await page.getByRole('textbox', { name: '메모 제목' }).fill('두 기기에서 이어지는 생각');
  await page.getByRole('textbox', { name: '메모 내용' }).fill('아직은 나만 보는 메모');
  await page.getByRole('button', { name: '닫기', exact: true }).click();
  await expect(page.locator('.sync-status')).toHaveText('동기화됨');
  const device = await browser.newContext();
  const second = await device.newPage();
  await second.goto('/');
  await second.getByRole('button', { name: '로그인', exact: true }).click();
  await second.getByRole('textbox', { name: '아이디', exact: true }).fill(username);
  await second.getByLabel('비밀번호', { exact: true }).fill(password);
  await second.getByRole('dialog').getByRole('button', { name: '로그인', exact: true }).click();
  await expect(second.getByText('두 기기에서 이어지는 생각', { exact: true })).toBeVisible();
  await second.getByRole('button', { name: '두 기기에서 이어지는 생각 열기', exact: true }).click();
  await second.getByRole('textbox', { name: '메모 내용' }).fill('두 번째 기기에서 수정한 생각');
  await second.getByRole('button', { name: '닫기', exact: true }).click();
  await expect(second.locator('.sync-status')).toHaveText('동기화됨');
  await page.locator('.sync-status').click();
  await expect(page.getByText('두 번째 기기에서 수정한 생각', { exact: true })).toBeVisible();
  await page.getByRole('button', { name: '두 기기에서 이어지는 생각 열기', exact: true }).click();
  await page.getByRole('combobox', { name: '공개 범위' }).selectOption('public');
  await expect(page.getByRole('combobox', { name: '공개 범위' })).toHaveValue('public');
  await page.getByRole('button', { name: '닫기', exact: true }).click();
  const visitorContext = await browser.newContext();
  const visitor = await visitorContext.newPage();
  await visitor.goto('/');
  await visitor.getByRole('button', { name: /둘러보기/ }).click();
  const shared = visitor.getByTestId('note-card').filter({ hasText: '두 기기에서 이어지는 생각' });
  await expect(shared).toBeVisible();
  await shared.getByRole('button', { name: '내 메모로 이어 쓰기', exact: true }).click();
  await expect(visitor.getByRole('combobox', { name: '공개 범위' })).toHaveValue('private');
  await visitor.getByRole('button', { name: '닫기', exact: true }).click();
  await page.getByRole('button', { name: '두 기기에서 이어지는 생각 열기', exact: true }).click();
  await page.getByRole('combobox', { name: '공개 범위' }).selectOption('private');
  await expect(page.getByRole('combobox', { name: '공개 범위' })).toHaveValue('private');
  await page.getByRole('button', { name: '닫기', exact: true }).click();
  await visitor.getByRole('button', { name: /둘러보기/ }).click();
  await expect(visitor.getByTestId('note-card').filter({ hasText: '두 기기에서 이어지는 생각' })).toHaveCount(0);
  await device.close(); await visitorContext.close();
});

test('offline simultaneous edits keep both versions after reconnect', async ({ page, browser, request }) => {
  const response = await request.post('http://localhost:8081/api/auth/register', { data: { username: 'conflict_' + Date.now(), password: 'teum-conflict-password' } });
  const session = await response.json();
  await page.addInitScript(s => localStorage.setItem('teum-session', JSON.stringify(s)), session);
  await page.goto('/');
  await page.getByRole('button', { name: '메모 작성…', exact: true }).click();
  await page.getByRole('textbox', { name: '메모 제목' }).fill('동시 수정');
  await page.getByRole('textbox', { name: '메모 내용' }).fill('원래 내용');
  await page.getByRole('button', { name: '닫기', exact: true }).click();
  await expect(page.locator('.sync-status')).toHaveText('동기화됨');
  const device = await browser.newContext();
  await device.addInitScript(s => localStorage.setItem('teum-session', JSON.stringify(s)), session);
  const offline = await device.newPage(); await offline.goto('/');
  await expect(offline.getByText('원래 내용', { exact: true })).toBeVisible();
  await device.setOffline(true);
  await offline.getByRole('button', { name: '동시 수정 열기', exact: true }).click();
  await offline.getByRole('textbox', { name: '메모 내용' }).fill('오프라인 수정본');
  await offline.getByRole('button', { name: '닫기', exact: true }).click();
  await page.getByRole('button', { name: '동시 수정 열기', exact: true }).click();
  await page.getByRole('textbox', { name: '메모 내용' }).fill('온라인 수정본');
  await page.getByRole('button', { name: '닫기', exact: true }).click();
  await expect(page.locator('.sync-status')).toHaveText('동기화됨');
  await device.setOffline(false);
  await expect(offline.getByRole('button', { name: '두 버전 보관' })).toBeVisible();
  await offline.getByRole('button', { name: '두 버전 보관' }).click();
  await expect(offline.getByText('온라인 수정본', { exact: true })).toBeVisible();
  await expect(offline.getByText('오프라인 수정본', { exact: true })).toBeVisible();
  await expect(offline.locator('.sync-status')).toHaveText('동기화됨');
  await device.close();
});
